courses/api/urls.py
from django.urls import path, include
from tastypie.api import Api
from api.models import UserResource 
# Post_commentResource, PostResource
# from api.models import CategoryResource, CourseResource
api = Api(api_name='v1')
api.register(UserResource())
# api.register(PostResource())
# api.register(Post_commentResource())

# api.register(CourseResource())
# api.register(CategoryResource())
urlpatterns = [
    path('', include(api.urls), name='index'),
    path('', include(api.urls), name='courses')
]

courses/base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<slug:slug>/', views.single_post, name='single_post'),
    path('tagged/', views.tagged, name='tagged')
]

courses/blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
import random,string


class Post(models.Model):
    moderation_complete = models.BooleanField(default=False)
    title = models.CharField(max_length=100)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=5)
    views_count = models.IntegerField(default=0)
    comments_count = models.IntegerField(default=0)
    created_at = models.DateField(default=timezone.now)
    post_rating = models.IntegerField(default=0)
    tags = TaggableManager()
    slug = models.SlugField(unique=True, db_index=True, verbose_name="URL", null=True,blank=True, max_length=100)

    def str(self):
        return f'{self.title}'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(''.join(random.choices(string.ascii_uppercase + string.digits, k=12)))
        super().save(*args, **kwargs)


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=5)
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.text}'

courses/blog/forms.py
from django import forms
from .models import Post, PostComment

class PostForm(forms.ModelForm):
    # title = forms.CharField(max_length=100)
    # text = forms.TimeField()
    # tag = TaggableManager()

    class Meta:
        model = Post
        fields = {'title', 'text', 'tags'}

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.TextInput(attrs={'class': 'form-control'})
        }

class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment 
        fields = {'text', 'user', 'post'}

courses/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, PostComment
from taggit.models import Tag
from .forms import PostForm, PostCommentForm
from django.utils import timezone
from django.shortcuts import redirect


def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.published_date = timezone.now()
            post.save()
    else:
        form = PostForm()
    return render(request, 'blog/post_create.html', {'form':form})


def single_post(request, slug):
    current_post = get_object_or_404(Post , slug = slug)
    tags = Tag.objects.filter(id = current_post.id)
    comments = PostComment.objects.filter(id = current_post.id)

    if request.method == "POST":
        # A comment was posted
        comment_form = PostCommentForm(request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            #new_comment.current_post = current_post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = PostCommentForm(initial={'post': current_post})        
    return render(request, 'blog/single_post.html', {'tags': tags, 'current_post': current_post,
                                                     'comments': comments, 'comment_form': comment_form,
                                                     'back_url': request.META.get('HTTP_REFERER')})


def index(request):
    return render(request, 'blog/home.html')


def tagged(request, slug):
    tag = get_object_or_404(Tag)
    # Filter posts by tag name  
    posts = Post.objects.filter(tags=tag)
    return render(request, 'blog/home.html', {'tag':tag, 'posts':posts})

courses/templates/blog/home.html
{% extends 'base.html' %}

{% block title %}All Posts{% endblock %} 

{% block content %}
{% comment %} <table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>views</th>
            <th>Comments</th>
            <th>Date of creation</th>
        </tr>
    </thead>
    <tbody>
        {% for post in Posts %}
        <tr>
            <td><a href={% url 'blog:single_post' post.slug%}>{{ post.title }}</a></td>
            <td>{{post.user}}</td>
            <td>{{post.views_count}}</td>
            <td>{{post.comments_count}}</td>
            <td>{{post.created_at}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table> {% endcomment %}
<div class="articles">
    <div class="article">
        <div class="article_name">
            Title
        </div>
        <div class="article_author">
                Author
        </div>
        <div class="article_view">
                Views
        </div>
        <div class="article_comment">
                Comments
        </div>
        <div class="article_date">
                Date of creation
        </div>
    </div>
    {% for post in Posts %}
    <div class="article">
        <div class="article_name">
            <a href={% url 'blog:single_post' post.slug%} class="link-style">{{ post.title }}</a>
        </div>
        <div class="article_author">
            {{post.user}}
        </div>
        <div class="article_view">
            {{post.views_count}}
            <i class="fa fa-eye">

            </i>
        </div>
        <div class="article_comment">
            {{post.views_count}}
        </div>
        <div class="article_date">
            {{post.created_at}}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

courses/templates/blog/post_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
    
    
    
    
 

courses/templates/blog/single_post.html
{% extends 'base.html' %}

{% block title %}{{current_post.title}}{% endblock %} 

{% block content %}
<h1 class="mt-5">{{current_post.title}}</h1>
<h2>{{current_post.title}}</h2>
<p>Tags:</p> 
{% for tag in tags %}
    <p>{{tag.name}}</p> 
{% endfor %}
<p>Views: {{current_post.views_count}}</p>
<p>Created at: {{current_post.created_at}}</p>
<p>Text: {{current_post.text}}</p>

{% comment %} {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %} {% endcomment %}

{% for comments in PostComments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Add comment</button>        
    </form>
{% endif %}


{% endblock %}